#!/usr/bin/env python3
"""Extract the v0.11.5 image-model labyrinth atlas into runtime assets.

The source atlas is a labelled composition generated by an image model. This
script crops each asset, removes the dark atlas background, filters label/noise
components, and writes the exact canvas sizes expected by the game.

Usage:
    python tools/extract-labyrinth-ai-atlas.py \
      asset-packs/cc0-pixel-v10/sources/labyrinth-ai-v0115/labyrinth-ai-atlas.png \
      asset-packs/cc0-pixel-v10/labyrinth
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Final

import numpy as np
from PIL import Image, ImageDraw, ImageFilter, ImageOps

CropSpec = tuple[tuple[int, int, int, int], tuple[int, int], bool]

BASE_CROPS: Final[dict[str, CropSpec]] = {
    "floor-01.png": ((12, 34, 140, 112), (256, 128), True),
    "floor-02.png": ((145, 34, 276, 112), (256, 128), True),
    "floor-03.png": ((280, 34, 407, 112), (256, 128), True),
    "fog.png": ((82, 194, 337, 270), (256, 128), True),
    "wall-northwest.png": ((10, 326, 195, 411), (256, 192), True),
    "wall-northeast.png": ((202, 326, 408, 411), (256, 192), True),
    "wall-southwest.png": ((10, 455, 195, 562), (256, 192), True),
    "wall-southeast.png": ((202, 455, 408, 562), (256, 192), True),
    "hero.png": ((938, 38, 1080, 201), (128, 128), True),
    "dragon.png": ((1098, 38, 1244, 201), (96, 96), True),
    "entrance.png": ((1300, 35, 1522, 205), (128, 128), True),
    "rune-vocabulary.png": ((935, 270, 1055, 403), (128, 128), True),
    "rune-comprehension.png": ((1063, 270, 1183, 403), (128, 128), True),
    "rune-grammar.png": ((1194, 270, 1312, 403), (128, 128), True),
    "rune-pronunciation.png": ((1330, 270, 1515, 403), (128, 128), True),
    "monster-01.png": ((15, 638, 123, 775), (192, 192), True),
    "monster-02.png": ((132, 630, 263, 775), (192, 192), True),
    "monster-03.png": ((280, 626, 405, 775), (192, 192), True),
    "guardian.png": ((430, 505, 647, 775), (256, 256), True),
    "trap-01.png": ((686, 505, 784, 580), (128, 128), True),
    "trap-02.png": ((793, 505, 894, 580), (128, 128), True),
    "trap-03.png": ((902, 505, 992, 580), (128, 128), True),
    "trap-04.png": ((1008, 505, 1092, 580), (128, 128), True),
    "cache-closed.png": ((1110, 505, 1198, 580), (128, 128), True),
    "cache-open.png": ((1212, 505, 1305, 580), (128, 128), True),
    "treasure-locked.png": ((1320, 505, 1408, 580), (128, 128), True),
    "treasure-open.png": ((1420, 505, 1528, 580), (128, 128), True),
    "healing-fountain.png": ((710, 650, 835, 778), (128, 128), True),
    "reveal-obelisk.png": ((862, 650, 983, 778), (128, 128), True),
    "decoration-01.png": ((12, 846, 100, 966), (96, 96), True),
    "decoration-02.png": ((110, 846, 198, 966), (96, 96), True),
    "decoration-03.png": ((215, 846, 305, 966), (96, 96), True),
    "decoration-04.png": ((312, 846, 405, 966), (96, 96), True),
    "decoration-05.png": ((420, 846, 515, 966), (96, 96), True),
    "decoration-06.png": ((528, 846, 635, 966), (96, 96), True),
    "map-backdrop.png": ((650, 838, 1085, 1009), (1280, 720), False),
    "encounter-backdrop.png": ((1098, 838, 1526, 1009), (1024, 360), False),
}


def build_crops() -> dict[str, CropSpec]:
    crops = dict(BASE_CROPS)
    centers_x = [480, 610, 740, 855]
    path_boxes_y = [(34, 106), (145, 212), (246, 302), (344, 402)]
    for row, (top, bottom) in enumerate(path_boxes_y):
        for column, center_x in enumerate(centers_x):
            index = row * 4 + column
            crops[f"path-{index:02d}.png"] = (
                (center_x - 48, top, center_x + 48, bottom),
                (256, 128),
                True,
            )
    return crops


def remove_atlas_background(crop: Image.Image) -> Image.Image:
    array = np.asarray(crop.convert("RGB"), dtype=np.float32)
    height, width, _ = array.shape
    yy, xx = np.mgrid[0:height, 0:width]
    border_width = max(3, min(height, width) // 18)
    border = np.zeros((height, width), dtype=bool)
    border[:border_width, :] = True
    border[-border_width:, :] = True
    border[:, :border_width] = True
    border[:, -border_width:] = True

    maximum = array.max(axis=2)
    minimum = array.min(axis=2)
    candidates = border & (maximum < 90) & ((maximum - minimum) < 40)
    if candidates.sum() < 30:
        candidates = border & (maximum < 120)

    design = np.stack(
        [np.ones(candidates.sum()), xx[candidates], yy[candidates]], axis=1
    )
    predicted = np.zeros_like(array)
    for channel in range(3):
        values = array[:, :, channel][candidates]
        if len(values) >= 3:
            coefficients = np.linalg.lstsq(design, values, rcond=None)[0]
        else:
            coefficients = np.array(
                [np.median(array[:, :, channel][border]), 0.0, 0.0]
            )
        predicted[:, :, channel] = (
            coefficients[0] + coefficients[1] * xx + coefficients[2] * yy
        )

    distance = np.sqrt(((array - predicted) ** 2).sum(axis=2))
    alpha = np.clip((distance - 9.0) / 25.0, 0.0, 1.0)
    alpha = np.maximum(alpha, np.clip((maximum - 35.0) / 100.0, 0.0, 1.0) * 0.25)
    alpha_image = Image.fromarray((alpha * 255).astype(np.uint8), "L")
    alpha_image = alpha_image.filter(ImageFilter.GaussianBlur(0.55))

    result = crop.convert("RGBA")
    result.putalpha(alpha_image)
    return result


def filter_components(image: Image.Image, filename: str) -> Image.Image:
    if filename in {"fog.png", "decoration-06.png"}:
        return image

    alpha = np.array(image.getchannel("A"))
    mask = alpha > 45
    height, width = mask.shape
    seen = np.zeros_like(mask, dtype=bool)
    components: list[list[tuple[int, int]]] = []

    for y in range(height):
        for x in range(width):
            if not mask[y, x] or seen[y, x]:
                continue
            stack = [(x, y)]
            seen[y, x] = True
            points: list[tuple[int, int]] = []
            while stack:
                px, py = stack.pop()
                points.append((px, py))
                for nx, ny in ((px - 1, py), (px + 1, py), (px, py - 1), (px, py + 1)):
                    if (
                        0 <= nx < width
                        and 0 <= ny < height
                        and mask[ny, nx]
                        and not seen[ny, nx]
                    ):
                        seen[ny, nx] = True
                        stack.append((nx, ny))
            components.append(points)

    if not components:
        return image

    components.sort(key=len, reverse=True)
    keep = np.zeros_like(mask, dtype=bool)

    if filename.startswith("path-"):
        points = np.array(components[0])
        keep[points[:, 1], points[:, 0]] = True
    else:
        largest = len(components[0])
        main_points = np.array(components[0])
        center_x = main_points[:, 0].mean()
        center_y = main_points[:, 1].mean()
        for points_list in components:
            points = np.array(points_list)
            area = len(points_list)
            component_x = points[:, 0].mean()
            component_y = points[:, 1].mean()
            distance = ((component_x - center_x) ** 2 + (component_y - center_y) ** 2) ** 0.5
            if area >= max(10, largest * 0.018) or (
                area >= 3 and distance < max(width, height) * 0.42
            ):
                keep[points[:, 1], points[:, 0]] = True

    keep_image = Image.fromarray((keep * 255).astype(np.uint8), "L")
    keep_image = keep_image.filter(ImageFilter.MaxFilter(3))
    new_alpha = np.minimum(alpha, np.array(keep_image))
    result = image.copy()
    result.putalpha(Image.fromarray(new_alpha.astype(np.uint8), "L"))
    return result


def fit_asset(image: Image.Image, size: tuple[int, int], filename: str) -> Image.Image:
    bounds = image.getchannel("A").getbbox()
    if bounds:
        image = image.crop(bounds)

    width, height = size
    margin = max(2, int(min(width, height) * 0.035))
    fitted = ImageOps.contain(
        image,
        (width - 2 * margin, height - 2 * margin),
        Image.Resampling.LANCZOS,
    )
    canvas = Image.new("RGBA", size, (0, 0, 0, 0))
    x = (width - fitted.width) // 2
    if filename.startswith(("floor-", "path-", "fog", "wall-")):
        y = (height - fitted.height) // 2
    else:
        y = height - margin - fitted.height
    canvas.alpha_composite(fitted, (x, max(0, y)))
    return canvas


def create_preview(output_dir: Path, filenames: list[str], destination: Path) -> None:
    thumbnails: list[Image.Image] = []
    for filename in filenames:
        image = Image.open(output_dir / filename).convert("RGBA")
        thumbnail = Image.new("RGBA", (180, 140), (28, 34, 31, 255))
        fitted = ImageOps.contain(image, (166, 108), Image.Resampling.LANCZOS)
        thumbnail.alpha_composite(
            fitted, ((180 - fitted.width) // 2, 4 + (108 - fitted.height) // 2)
        )
        ImageDraw.Draw(thumbnail).text((4, 118), filename, fill=(240, 240, 220, 255))
        thumbnails.append(thumbnail)

    columns = 6
    rows = (len(thumbnails) + columns - 1) // columns
    sheet = Image.new("RGBA", (columns * 180, rows * 140), (18, 22, 20, 255))
    for index, thumbnail in enumerate(thumbnails):
        sheet.alpha_composite(
            thumbnail, ((index % columns) * 180, (index // columns) * 140)
        )
    sheet.save(destination)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source_atlas", type=Path)
    parser.add_argument("output_directory", type=Path)
    parser.add_argument("--preview", type=Path)
    args = parser.parse_args()

    source = Image.open(args.source_atlas).convert("RGB")
    if source.size != (1536, 1024):
        raise SystemExit(
            f"Expected a 1536x1024 source atlas, received {source.width}x{source.height}."
        )

    args.output_directory.mkdir(parents=True, exist_ok=True)
    crops = build_crops()
    for filename, (box, size, transparent) in crops.items():
        crop = source.crop(box)
        if transparent:
            asset = fit_asset(
                filter_components(remove_atlas_background(crop), filename),
                size,
                filename,
            )
        else:
            asset = ImageOps.fit(
                crop,
                size,
                Image.Resampling.LANCZOS,
                centering=(0.5, 0.5),
            ).convert("RGB")
        asset.save(args.output_directory / filename)

    if args.preview:
        create_preview(args.output_directory, sorted(crops), args.preview)

    print(f"Extracted {len(crops)} assets to {args.output_directory}")


if __name__ == "__main__":
    main()
