#!/usr/bin/env node
import { copyFile, mkdir, readdir, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const packId = process.argv[2] ?? process.env.HLC_ASSET_PACK ?? "cc0-pixel-v10";
const source = path.join(root, "asset-packs", packId);
const destination = path.join(root, "apps", "web", "public", "assets", "pixel");

const ALLOWED_EXTENSIONS = new Set([".png", ".webp", ".json", ".yaml", ".yml", ".md", ".txt"]);
const IGNORED_DIRECTORIES = new Set(["sources", ".git", "node_modules"]);

async function exists(target) {
  try {
    await stat(target);
    return true;
  } catch {
    return false;
  }
}

async function copyTree(fromDir, toDir, relative = "") {
  await mkdir(toDir, { recursive: true });
  const entries = await readdir(fromDir, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.name.startsWith(".")) continue;
    const from = path.join(fromDir, entry.name);
    const to = path.join(toDir, entry.name);
    const childRelative = path.join(relative, entry.name);
    if (entry.isDirectory()) {
      if (IGNORED_DIRECTORIES.has(entry.name)) continue;
      await copyTree(from, to, childRelative);
      continue;
    }
    if (!entry.isFile()) continue;
    const extension = path.extname(entry.name).toLowerCase();
    if (!ALLOWED_EXTENSIONS.has(extension)) continue;
    await mkdir(path.dirname(to), { recursive: true });
    await copyFile(from, to);
    copied.push(childRelative);
  }
}

const copied = [];

if (!(await exists(source))) {
  console.error(`Asset pack not found: ${source}`);
  process.exit(1);
}

await rm(destination, { recursive: true, force: true });
await mkdir(destination, { recursive: true });
await copyTree(source, destination);
await writeFile(
  path.join(destination, "SYNCED-ASSET-PACK.txt"),
  `This folder is generated by tools/sync-assets.mjs.\n` +
    `Source pack: asset-packs/${packId}\n` +
    `Do not hand-edit files here unless you also copy them back to the asset pack.\n`,
  "utf8"
);

console.log(`Synced ${copied.length} asset files from asset-packs/${packId} to apps/web/public/assets/pixel.`);
